const path = require('path');
const fs = require('fs');
//use path library to create path to .sol file (irrespective of OS).
const lotteryPath = path.resolve(__dirname, 'contracts', 'Lottery.sol');
const solc = require('solc');
const source = fs.readFileSync(lotteryPath, 'utf8');
//log compile output
console.log(solc.compile(source, 1));

//now in cmd with project main folder as CD, type:

// in cmd log, we see a JSON returned which contains various info like bytecode, interface etc of solidity contract.
// the bytecode of .sol file resides in JSON returned under contracts[':Inbox'] subtree,
// therefore to specifically get bytecode, change line 17 to:

module.exports = solc.compile(source, 1).contracts[':Lottery'];  //export the JSON generated by compile method.